// flow-typed signature: ed8af100ff415cf4c6cf5a59f30e26d4
// flow-typed version: <<STUB>>/babel-preset-es2015-rollup_v^1.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-rollup/index' {
  declare module.exports: $Exports<'babel-preset-es2015-rollup'>;
}
declare module 'babel-preset-es2015-rollup/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-rollup'>;
}
